# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'none'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu: 
  - name: Featured Projects
    submenu:
      - name: ICS APT and Malware Families List
        link: /projects/aptmalwarelist
    - name: About
    link: /about
  - name: Tags
    link: /tags


    
